- name: restart switchd
  service: name=switchd state=restarted
  service: name=networking state=reloaded

- name: reload networking
  service: name=networking state=reloaded

- name: restart ptmd
  service: name=ptmd state=restarted

- name: restart quagga
  service: name=quagga state=restarted
